export const FormatTemplateFields = {
  EVENT_TYPE: "EVENT_TYPE",
  VALIDATION_TYPE: "VALIDATION_TYPE",
  NAME: "NAME",
  ID: "ID",
  TIME_STAMP: "TIME_STAMP",
  SOURCE: "SOURCE",
  CONTEXT: "CONTEXT",
  MESSAGE: "MESSAGE",
  DETAILS: "DETAILS",
  STACK: "STACK",
  USER_ID: "USER_ID",
} as const;
